# Generated by Django 2.2.12 on 2020-05-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requestor', models.CharField(max_length=200)),
                ('dateRequested', models.DateField()),
                ('customer', models.CharField(max_length=400)),
            ],
        ),
    ]
