# Generated by Django 2.2.12 on 2020-05-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewrequest',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Medium'), (2, 'High')], default=1),
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='requestor',
            field=models.CharField(max_length=10),
        ),
    ]
