# Generated by Django 2.2.12 on 2020-05-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reviews', '0002_auto_20200521_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='reviewrequest',
            name='requestor',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='reviewrequest',
            name='reviewType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Reviews.ReviewType'),
        ),
    ]
